/*
 * This source file was generated by the Gradle 'init' task
 */
package com.kimikevin;

public class App {

    public static void main(String[] args) throws Exception {
//        RuntimeException exception = new RuntimeException("Something went wrong");
//        throw exception;
        System.out.println(Class.forName(String.class.getClass().getName()));
    }
}
