/*
 * This source file was generated by the Gradle 'init' task
 */
package com.kimikevin;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        assertNotNull("app should have a greeting");
    }
}
